# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "vStone/centos-7.x-puppet.3.x"

  config.vm.network "forwarded_port", guest: 80, host: 7081

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  # Enable provisioning with a shell script.
  config.vm.provision "shell", inline: <<-EOF
     yum install nginx -y --enablerepo=epel
     systemctl start nginx
     firewall-cmd --add-service=http
  EOF
end
